package com.daam.recruitment.enumeration;

import java.util.Arrays;
import java.util.List;
import java.util.Optional;

/**
 * Fixed list of recruitment job titles (poste / titre).
 */
public enum JobTitle {
    ADMINISTRATEUR_DES_ACHATS("ADMINISTRATEUR DES ACHATS"),
    AGENT_DE_MENAGE("AGENT DE MÉNAGE"),
    AGENT_DE_SECURITE("AGENT DE SÉCURITÉ"),
    ANALYSTE_DE_CREDIT("ANALYSTE DE CRÉDIT"),
    ANALYSTE_DE_CREDIT_SENIOR("ANALYSTE DE CRÉDIT SÉNIOR"),
    ANALYSTE_DES_DONNEES("ANALYSTE DES DONNÉES"),
    ANALYSTE_ORGANISATION_METHODE("ANALYSTE ORGANISATION & MÉTHODE"),
    ASSISTANT_BACK_OFFICE_ET_JURIDIQUE("ASSISTANT(E) BACK-OFFICE ET JURIDIQUE"),
    ASSISTANTE_DE_DIRECTION("ASSISTANTE DE DIRECTION"),
    AUDITEUR_INTERNE("AUDITEUR INTERNE"),
    CAISSIER("CAISSIER(E)"),
    CHARGE_ADMINISTRATIF("CHARGÉ(E) ADMINISTRATIF"),
    CHARGE_AU_CENTRE_D_APPEL("CHARGÉ(E) AU CENTRE D'APPEL"),
    CHARGE_AU_SERVICE_A_LA_CLIENTELE("CHARGÉ(E) AU SERVICE À LA CLIENTÈLE"),
    CHARGE_CONFORMITE_ET_CONTROLE_INTERNE("CHARGÉ(E) CONFORMITÉ ET CONTRÔLE INTERNE"),
    CHARGE_DE_CLASSEMENT("CHARGÉ(E) DE CLASSEMENT"),
    CHARGE_DE_CONTENTIEUX("CHARGÉ(E) DE CONTENTIEUX"),
    CHARGE_DE_CREDIT("CHARGÉ(E) DE CRÉDIT"),
    CHARGE_DE_FORMATION_ET_ACCOMPAGNEMENT("CHARGÉ(E) DE FORMATION ET ACCOMPAGNEMENT"),
    CHARGE_DE_RECOUVREMENT("CHARGÉ(E) DE RECOUVREMENT"),
    CHARGE_DE_SAISIE_DE_DONNEES("CHARGÉ(E) DE SAISIE DE DONNÉES"),
    CHARGE_DE_SAISIE_DE_DONNEES_SENIOR("CHARGÉ(E) DE SAISIE DE DONNÉES SÉNIOR"),
    CHARGE_D_ENREGISTREMENT_DES_GARANTIES("CHARGÉ(E) D'ENREGISTREMENT DES GARANTIES"),
    CHARGE_OPERATION("CHARGÉ(E) OPÉRATION"),
    CHARGE_SUPPORT_SYSTEME("CHARGÉ(E) SUPPORT SYSTÈME"),
    CHAUFFEUR("CHAUFFEUR"),
    CHEF_D_AGENCE("CHEF D'AGENCE"),
    CHEF_DU_PARK("CHEF DU PARC"),
    COMPTABLE("COMPTABLE"),
    COMPTABLE_SENIOR("COMPTABLE SÉNIOR"),
    CONSEILLER_SENIOR_EN_CONFORMITE_ET_CONTROLE_INTERNE("CONSEILLER SÉNIOR EN CONFORMITÉ ET CONTRÔLE INTERNE"),
    CONSEILLER_AUX_RESSOURCES_HUMAINES("CONSEILLER(E) AUX RESSOURCES HUMAINES"),
    CONSEILLER_SENIOR_EN_COMMUNICATION("CONSEILLER(E) SÉNIOR EN COMMUNICATION"),
    CONSEILLERE_SENIOR_RISQUE_ET_CONFORMITE("CONSEILLÈRE SÉNIOR RISQUE ET CONFORMITÉ"),
    CONTROLEUR_DE_GESTION("CONTRÔLEUR DE GESTION"),
    COORDINATEUR_SERVICES_GENERAUX("COORDINATEUR SERVICES GÉNÉRAUX"),
    DIRECTEUR_BACK_OFFICE_ET_JURIDIQUE("DIRECTEUR BACK-OFFICE ET JURIDIQUE"),
    DIRECTEUR_DE_CREDIT("DIRECTEUR DE CRÉDIT"),
    DIRECTEUR_DES_FINANCES("DIRECTEUR DES FINANCES"),
    DIRECTEUR_DES_RESSOURCES_HUMAINES_ET_SI("DIRECTEUR DES RESSOURCES HUMAINES ET SI"),
    DIRECTEUR_GENERAL("DIRECTEUR GÉNÉRAL"),
    DIRECTRICE_EXECUTIVE_DE_LA_FONDATION_DAAM("DIRECTRICE EXÉCUTIVE DE LA FONDATION DAAM"),
    GESTIONNAIRE_DES_LIQUIDITES("GESTIONNAIRE DES LIQUIDITÉS"),
    INFOGRAPHISTE("INFOGRAPHISTE"),
    RECEPTIONNISTE("RÉCEPTIONNISTE"),
    RESPONSABLE_BACK_OFFICE_ET_JURIDIQUE("RESPONSABLE BACK-OFFICE ET JURIDIQUE"),
    RESPONSABLE_COMMUNICATION("RESPONSABLE COMMUNICATION"),
    RESPONSABLE_COMPTABLE("RESPONSABLE COMPTABLE"),
    RESPONSABLE_CONTENTIEUX("RESPONSABLE CONTENTIEUX"),
    RESPONSABLE_DE_CREDIT("RESPONSABLE DE CRÉDIT"),
    RESPONSABLE_DES_FINANCES("RESPONSABLE DES FINANCES"),
    RESPONSABLE_DES_MOYENS_GENERAUX("RESPONSABLE DES MOYENS GÉNÉRAUX"),
    RESPONSABLE_DES_OPERATIONS("RESPONSABLE DES OPÉRATIONS"),
    RESPONSABLE_DES_RISQUES_DE_CREDIT("RESPONSABLE DES RISQUES DE CRÉDIT"),
    RESPONSABLE_DEVELOPPEMENT_COMMERCIAL("RESPONSABLE DÉVELOPPEMENT COMMERCIAL"),
    RESPONSABLE_INFORMATIQUE("RESPONSABLE INFORMATIQUE"),
    RESPONSABLE_ORGANISATION_ET_METHODES("RESPONSABLE ORGANISATION ET MÉTHODES"),
    RESPONSABLE_PRECONTENTIEUX("RESPONSABLE PRÉCONTENTIEUX"),
    SUPERVISEUR("SUPERVISEUR"),
    SUPERVISEUR_DU_CENTRE_DE_CONTACT("SUPERVISEUR DU CENTRE DE CONTACT"),
    TECHNICIEN_SUPPORT_IT("TECHNICIEN SUPPORT IT"),
    CHARGE_DES_IMMOBILISATIONS("CHARGÉ(E) DES IMMOBILISATIONS"),
    CHARGE_DES_MOYENS_GENERAUX("CHARGÉ(E) DES MOYENS GÉNÉRAUX"),
    CHARGE_DE_PROJET_ONG("CHARGÉ(E) DE PROJET - ONG"),
    CHARGE_RECLAMATION("CHARGÉ(E) RÉCLAMATION"),
    CHARGE_MARKETING_DIGITAL("CHARGÉ(E) MARKETING DIGITAL"),
    CHARGE_ARCHIVE("CHARGÉ(E) ARCHIVE");

    private final String label;

    JobTitle(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }

    public static List<String> labels() {
        return Arrays.stream(values()).map(JobTitle::getLabel).toList();
    }

    public static Optional<JobTitle> fromLabel(String label) {
        if (label == null || label.isBlank()) {
            return Optional.empty();
        }
        String normalized = label.trim();
        return Arrays.stream(values())
                .filter(t -> t.label.equalsIgnoreCase(normalized))
                .findFirst();
    }

    public static boolean isValidLabel(String label) {
        return fromLabel(label).isPresent();
    }
}
